name: multi_cloud_storage
description: A Flutter package that integrates Google Drive, iCloud, Dropbox, and OneDrive via their respective plugins.
version: 0.8.1
homepage: https://github.com/chris-wolf/multi_cloud_storage

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^14.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  google_sign_in: ^6.3.0
  flutter_onedrive: ^1.8.1
  path: ^1.9.1
  http: ^1.4.0
  flutter_web_auth_2: ^4.1.0
  url_launcher: ^6.3.2
  dio: ^5.9.0
  crypto: ^3.0.6
  app_links: ^6.4.1
  flutter_secure_storage: ^9.2.4
  icloud_storage_sync:
    path: ../icloud_storage_sync
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  flutter_inappwebview: ^6.1.5
  googleapis_auth: ^1.4.1
  google_sign_in_all_platforms: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

platforms:
  android:
  ios:
  macos:
  windows:

screenshots:
  - description: 'Example cloud explorer'
    path: example/screenshots/Example_cloud_storage_explorer.jpg
